# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app

COPY portfolio-frontend/package*.json ./
RUN npm install

COPY portfolio-frontend/. .
RUN npm run build

# Stage 2: Production
FROM nginx:alpine

COPY --from=builder /app/out /usr/share/nginx/html

# Copy custom nginx config
COPY portfolio-frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]